# Generated by Django 5.1.3 on 2024-11-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_release_date_alter_album_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
    ]
